FROM node:16.13.0

WORKDIR /usr/src/app

COPY ./.env ./
COPY ./public ./public
COPY ./src ./src
COPY ./craco* ./
COPY ./package* ./
COPY ./tsconfig* ./
COPY ./.eslint* ./

RUN npm i \
    && npm run build\