version: '3.7'

services:
  nginx:
    image: nginx
    container_name: boocam-nginx
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ./nginx/nginx-prod/build:/usr/share/nginx/html
      - ./nginx/nginx-prod/nginx:/etc/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
  pm2:
    image: keymetrics/pm2:16-jessie
    container_name: boocam-pm2
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ./node/dist:/dist
    command: sh -c "ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && pm2 start /dist/app.js -f -i max && tail -f /dev/null"
  mysql:
    image: mysql:5.7.36
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qnzoadnlzl
  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email boocamwiki@gmail.com --agree-tos --no-eff-email -d boocamwiki.kr
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
      - ./certbot/logs:/var/log/letsencrypt
