name: production deploy

on:
  push:
    branches: [develop, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_FOLDER: boocam_wiki

    steps:
      - name: ssh connect & production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          envs: PROJECT_FOLDER
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd $PROJECT_FOLDER
            git fetch
            git pull origin
            ./scripts/start.sh
            cd ../server
            npm i
            npm run build
            cd ../docker
            mv -f nginx-prod/* nginx/nginx
            docker exec docker_pm2_1 pm2 reload /dist/app.js
            docker exec docker_nginx_1 service nginx reload
